version: "3"

services:

  app:
    build: .
    env_file:
      - ./local.env
    volumes:
      - ./:/src
      - go-build:/home/user/.cache/go-build
      - go-mod:/home/user/go/pkg/mod
    command: ./build.sh cli

volumes:
  go-build: {}
  go-mod: {}
